config/routes.rb
Rails.application.routes.draw do
  resources :action_objects
  resources :professions

  resources :procurements
  root 'welcome#index'

end

app/models/action_object.rb
class ActionObject < ActiveRecord::Base
end

app/controllers/action_objects_controller.rb
class ActionObjectsController < ApplicationController
  before_action :set_action_object, only: [:show, :edit, :update, :destroy]

  # GET /action_objects
  # GET /action_objects.json
  def index
    @action_objects = ActionObject.all
    @action_objects = ActionObject.order :objeto
    render "index"
  end

  # GET /action_objects/1
  # GET /action_objects/1.json
  def show
  end

  # GET /action_objects/new
  def new
    @action_object = ActionObject.new
  end

  # GET /action_objects/1/edit
  def edit
  end

  # POST /action_objects
  # POST /action_objects.json
  def create
    @action_object = ActionObject.new(action_object_params)

    respond_to do |format|
      if @action_object.save
        format.html { redirect_to action: 'index', notice: 'Objeto de Ação criado com sucesso.' }
        format.json { render :show, status: :created, location: @action_object }
      else
        format.html { render :new }
        format.json { render json: @action_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /action_objects/1
  # PATCH/PUT /action_objects/1.json
  def update
    respond_to do |format|
      if @action_object.update(action_object_params)
        format.html { redirect_to action: 'index', notice: 'Objeto de Ação alterado com sucesso.'}
        format.json { render :show, status: :ok, location: @action_object }
      else
        format.html { render :edit }
        format.json { render json: @action_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /action_objects/1
  # DELETE /action_objects/1.json
  def destroy
    @action_object.destroy
    respond_to do |format|
      format.html { redirect_to action_objects_url, notice: 'Objeto de Ação apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_action_object
      @action_object = ActionObject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def action_object_params
      params.require(:action_object).permit(:objeto)
    end
end

app/helpers/action_objects_helper.rb
module ActionObjectsHelper
end

app/views/action_objects/_form.html.erb
<%= form_for @action_object, :html => {:id => "myForm"} do |f| %>
  <% if @action_object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action_object.errors.count, "error") %> ao salvar Objeto de Ação.</h2>

      <ul>
      <% @action_object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="row">
		<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
			<%= f.label :objeto_de_ação %>
			<br>
			<%= f.text_field :objeto %>
		</div>
	</div>
<% end %>

app/views/action_objects/edit.html.erb
<table class="table">
	<tr>
		<td>
			<%= image_tag("LogoGSAdvogados.png") %>
		</td>
	</tr>
	<tr>
		<td style="text-align:left">
			<h3>Editar Objeto de Ação</h3>
		</td>
	</tr>
</table>
<div class="navbar navbar-fixed-bottom container">
	<button id="saveButton" class="btn btn-primary glyphicon glyphicon-floppy-disk"> Salvar</button>
	<%= link_to ' Lista de Procurações', procurements_path, class: 'btn btn-default glyphicon glyphicon-list-alt' %>
	<%= link_to ' Voltar', action_objects_path, class: 'btn btn-default glyphicon glyphicon-arrow-left' %>
</div>
<%= render 'form' %>

app/views/action_objects/index.html.erb
<table class="table">
	<div class="navbar navbar-fixed-bottom container">
		<%= link_to 'Voltar', procurements_path, class: 'btn btn-default glyphicon glyphicon-arrow-left' %>
	</div>
	<tr>
		<td>
			<%= image_tag("LogoGSAdvogados.png") %>
		</td>
	</tr>
	<tr>
		<td style="text-align:left">
			<%= link_to ' Novo Objeto de Ação', new_action_object_path, class: 'btn btn-default glyphicon glyphicon-plus' %>
		</td>
	</tr>
</table>
<table class="table table-condensed">
	<% flash.each do |type, content| %>
    <% if content.respond_to?('each') 
        content.each do |item| %>
            <%= render 'layouts/alert', 
                type: type,
                content: item %>
        <% end %>
    <% else %>
        <%= render 'layouts/alert', 
                type: type,
                content: content %>
    <% end %>

<% end %>
  <thead>
		<tr>
			<th style="text-align:center"> Profissão</th>
			<th style="text-align:center"> Editar </th>
			<th style="text-align:center"> Excluir </th>
		</tr>
	</thead>
  	<% if @action_objects.empty? %>
		<tr>
			<td colspan="3">
				<br>
				<font color="red" style="bold">Nenhum Objeto de Ação cadastrado.</font>
			</td>
		</tr>
	<% else %>
	    <% @action_objects.each do |action_object| %>
	      <tr>
	        <td><%= action_object.objeto %></td>
	        <td align="center"><%= link_to ' ', edit_action_object_path(action_object), 
	        	class: 'glyphicon glyphicon-pencil' %></td>
	        <td align="center"><%= link_to action_object_path(action_object), 
				method: :delete,
				data: { confirm: 'Tem certeza?' } do %>
				<span class="glyphicon glyphicon-trash"></span>
			<% end %></td>
	      </tr>
	    <% end %>
   <% end %>
</table>

app/views/action_objects/new.html.erb
<table class="table">
	<tr>
		<td>
			<%= image_tag("LogoGSAdvogados.png") %>
		</td>
	</tr>
	<tr>
		<td style="text-align:left">
			<h3>Novo Objeto de Ação</h3>
		</td>
	</tr>
</table>
<div class="navbar navbar-fixed-bottom container">
	<button id="saveButton" class="btn btn-primary glyphicon glyphicon-floppy-disk"> Salvar</button>
	<%= link_to ' Lista de Procurações', procurements_path, class: 'btn btn-default glyphicon glyphicon-list-alt' %>
	<%= link_to ' Voltar', action_objects_path, class: 'btn btn-default glyphicon glyphicon-arrow-left' %>
</div>
<%= render 'form' %>

app/views/action_objects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Objeto:</strong>
  <%= @action_object.objeto %>
</p>

<%= link_to 'Edit', edit_action_object_path(@action_object) %> |
<%= link_to 'Back', action_objects_path %>