config/routes.rb
Rails.application.routes.draw do
  resources :action_objects
  resources :professions

  resources :procurements
  root 'welcome#index'

end

app/models/procurement.rb
class Procurement < ActiveRecord::Base
  validates :cliente, presence: true, length: { minimum: 3 }
  validates :observacoes_complementares , length: { maximum: 400 }
  
  def self.search(search)
    where("cliente LIKE ? or cast(numero_do_processo as text) LIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/procurements_controller.rb
class ProcurementsController < ApplicationController
  
 # http_basic_authenticate_with name: "gs", password: "gs"
    
  def index
     @procurements = Procurement.all
    if params[:search]
       @procurements = Procurement.search(params[:search]).order("created_at DESC")
     else
       @procurements = Procurement.all.order('created_at DESC')
     end
      respond_to do |format|
           format.html
       end
     
   end
  def show
      @procurement = Procurement.find(params[:id])
      respond_to do |format|
        format.html
        format.pdf do
          pdf = ReportPdf.new(@procurement)
          send_data pdf.render, filename: "Ficha_#{@procurement.cliente}.pdf", type: 'application/pdf'
        end
        format.pdf2 do
          pdf2 = ReportPdf2.new(@procurement)
          send_data pdf2.render, filename: "Procuracao_#{@procurement.cliente}.pdf", type: 'application/pdf'
        end
        format.pdf3 do
          pdf3 = ReportPdf3.new(@procurement)
          send_data pdf3.render, filename: "Contrato_#{@procurement.cliente}.pdf", type: 'application/pdf'
        end
      end
    end
     
  def new
    @procurement = Procurement.new
    @maximum_length = Procurement.validators_on( :observacoes_complementares ).first.options[:maximum]
  end
  
  def edit
    @procurement = Procurement.find(params[:id])
    @maximum_length = Procurement.validators_on( :observacoes_complementares ).first.options[:maximum]
  end
  
  def create
    @procurement = Procurement.new(procurement_params)
    if @procurement.save
      flash[:sucess] = 'Ficha criada com sucesso'
     redirect_to procurements_path
    else
      flash[:danger] = 'Não foi possível criar Ficha'
      render 'new'
    end
  end
  
  def update
    @procurement = Procurement.find(params[:id])
   
    if @procurement.update(procurement_params)
      flash[:sucess] = 'Ficha atualizada com sucesso'
     redirect_to procurements_path
    else
      flash[:danger] = 'Não foi possível atualizar a Ficha'
      render 'edit'
    end
  end
  
  def destroy
    @procurement = Procurement.find(params[:id])
    if @procurement.destroy
      flash[:sucess] = 'Ficha apagada com sucesso'
      redirect_to procurements_path
      else
        flash[:danger] = 'Ocorreu uma falha ao apagar a Ficha, tente novamente'
        end
  end
  
  private
    def procurement_params
      params.require(:procurement).permit!
    end
end

app/helpers/procurements_helper.rb
module ProcurementsHelper
end

app/views/procurements/edit.html.erb
<h3> Editar Ficha</h3>
<div class="navbar navbar-fixed-bottom container">
	<button id="saveButton" class="btn btn-primary glyphicon glyphicon-floppy-disk">Salvar</button>
	<%= link_to 'Ficha', procurement_path(@procurement, :format => 'pdf'), class: 'btn btn-default glyphicon glyphicon glyphicon-list-alt'  %>
	<%= link_to 'Procuração', procurement_path(@procurement, :format => 'pdf2'), class: 'btn btn-default glyphicon glyphicon-file' %>
	<%= link_to 'Contrato', procurement_path(@procurement, :format => 'pdf3'), class: 'btn btn-default glyphicon glyphicon-folder-close'  %>
	<%= link_to 'Voltar', procurements_path, class: 'btn btn-default glyphicon glyphicon-arrow-left' %>
</div>
<%= render 'form' %>

app/views/procurements/index.html.erb
<table class="table">
	<tr>
		<td>
			<%= image_tag("LogoGSAdvogados.png") %>
		</td>
	</tr>
	<tr>
		<td style="text-align:left">
			<%= link_to ' Novo Cadastro', new_procurement_path, class: 'btn btn-default glyphicon glyphicon-plus' %>
			<%= link_to 'Profissões', professions_path, class: 'btn btn-default glyphicon' %>
			<%= link_to 'Objeto de Ação', action_objects_path, class: 'btn btn-default glyphicon' %>
		</td>
		<td style="text-align: right">
			<%= form_tag(procurements_path, :method => "get", id: "search-form") do %>
				<%= text_field_tag :search, params[:search], placeholder: "Buscar por Nome ou Número do Processo" %>
				<%= button_tag(type: "submit", class: "btn btn-default") do %>
					<i class="glyphicon glyphicon-search"></i>
				<% end %>
				<%= link_to procurements_path,  class: 'btn btn-default' do %>
				<span class="glyphicon glyphicon-remove"></span>
				<% end %>
			<% end %>
		</td>
	</tr>
</table>
<table class="table table-condensed">
	<% flash.each do |type, content| %>
    <% if content.respond_to?('each') 
        content.each do |item| %>
            <%= render 'layouts/alert', 
                type: type,
                content: item %>
        <% end %>
    <% else %>
        <%= render 'layouts/alert', 
                type: type,
                content: content %>
    <% end %>

<% end %>
	<thead>
		<tr>
			<th style="text-align:center"> Cliente</th>
			<th style="text-align:center"> Processo </th>
			<th style="text-align:center"> Visualizar </th>
			<th style="text-align:center"> Editar </th>
			<th colspan="3" style="text-align:center"> Documentos </th>
			<!-- <th style="text-align:center"> Anexar </th> -->
			<th style="text-align:center"> Excluir </th>
		</tr>
	</thead>
	<% @procurements.each do |procurement| %>
	<tr>
		<td><%= procurement.cliente %></td>
		<td><%= procurement.numero_do_processo %></td>
		<td align="center"><%= link_to ' ', procurement_path(procurement), class: 'glyphicon glyphicon-eye-open' %></td>
		<td align="center"><%= link_to ' ', edit_procurement_path(procurement), class: 'glyphicon glyphicon-pencil' %></td>
		<td align="center"><%= link_to ' Ficha', procurement_path(procurement, :format => 'pdf'), class: 'glyphicon glyphicon glyphicon-list-alt'  %></td>
		<td align="center"><%= link_to ' Procuração', procurement_path(procurement, :format => 'pdf2'), 
			class: 'glyphicon glyphicon-file' %>
		</td>
		<td align="center"><%= link_to ' Contrato', procurement_path(procurement, :format => 'pdf3'), 
			class: 'glyphicon glyphicon glyphicon-folder-close' %>
		</td>
		<!-- <td align="center"><%= link_to ' ', edit_procurement_path(procurement), class: 'glyphicon glyphicon-paperclip' %></td> -->
		<td align="center"><%= link_to procurement_path(procurement), 
			method: :delete,
			data: { confirm: 'Tem certeza?' } do %>
			<span class="glyphicon glyphicon-trash"></span>
			<% end %></td>
	</tr>
	<% end %>
	</table>

app/views/procurements/new.html.erb
<h3> Criar Ficha </h3>
<div class="navbar navbar-fixed-bottom container">
	<button id="saveButton" class="btn btn-primary glyphicon glyphicon-floppy-disk"> Salvar</button>
	<%= link_to ' Voltar', procurements_path, class: 'btn btn-default glyphicon glyphicon-arrow-left' %>
</div>
<%= render 'form' %>