config/routes.rb
Rails.application.routes.draw do
  resources :action_objects
  resources :professions

  resources :procurements
  root 'welcome#index'

end

app/models/profession.rb
class Profession < ActiveRecord::Base
end

app/controllers/professions_controller.rb
class ProfessionsController < ApplicationController
  before_action :set_profession, only: [:show, :edit, :update, :destroy]

  # GET /professions
  # GET /professions.json
  def index
    @professions = Profession.all
    @professions = Profession.order :profissao
    render "index"
  end

  # GET /professions/1
  # GET /professions/1.json
  def show
  end

  # GET /professions/new
  def new
    @profession = Profession.new
  end

  # GET /professions/1/edit
  def edit
  end

  # POST /professions
  # POST /professions.json
  def create
    @profession = Profession.new(profession_params)

    respond_to do |format|
      if @profession.save
        format.html { redirect_to action: 'index', notice: 'Profissão criada com sucesso.' }
        format.json { render :show, status: :created, location: @profession }
      else
        format.html { render :new }
        format.json { render json: @profession.errors, status: :unprocessable_entity }
      end
      
    end
    
  end

  # PATCH/PUT /professions/1
  # PATCH/PUT /professions/1.json
  def update
    respond_to do |format|
      if @profession.update(profession_params)
        format.html { redirect_to action: 'index', notice: 'Profissão alterada com sucesso.' }
        format.json { render :show, status: :ok, location: @profession }
      else
        format.html { render :edit }
        format.json { render json: @profession.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professions/1
  # DELETE /professions/1.json
  def destroy
    @profession.destroy
    respond_to do |format|
      format.html { redirect_to professions_url, notice: 'Profissão apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profession
      @profession = Profession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profession_params
      params.require(:profession).permit(:profissao)
    end
end

app/helpers/professions_helper.rb
module ProfessionsHelper
end

app/views/professions/_form.html.erb
<%= form_for @profession, :html => {:id => "myForm"} do |f| %>
  <% if @profession.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profession.errors.count, "error") %> ao salvar Profissão:</h2>

      <ul>
      <% @profession.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="row">
		<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
			<%= f.label :profissão %>
			<br>
			<%= f.text_field :profissao %>
		</div>
	</div>
<% end %>

app/views/professions/edit.html.erb
<table class="table">
	<tr>
		<td>
			<%= image_tag("LogoGSAdvogados.png") %>
		</td>
	</tr>
	<tr>
		<td style="text-align:left">
			<h3>Editar Profissão</h3>
		</td>
	</tr>
</table>
<div class="navbar navbar-fixed-bottom container">
	<button id="saveButton" class="btn btn-primary glyphicon glyphicon-floppy-disk"> Salvar</button>
	<%= link_to ' Lista de Procurações', procurements_path, class: 'btn btn-default glyphicon glyphicon-list-alt' %>
	<%= link_to ' Voltar', professions_path, class: 'btn btn-default glyphicon glyphicon-arrow-left' %>
</div>
<%= render 'form' %>

app/views/professions/index.html.erb
<table class="table">
	<div class="navbar navbar-fixed-bottom container">
		<%= link_to 'Voltar', procurements_path, class: 'btn btn-default glyphicon glyphicon-arrow-left' %>
	</div>
	<tr>
		<td>
			<%= image_tag("LogoGSAdvogados.png") %>
		</td>
	</tr>
	<tr>
		<td style="text-align:left">
			<%= link_to ' Nova Profissão', new_profession_path, class: 'btn btn-default glyphicon glyphicon-plus' %>
		</td>
	</tr>
</table>
<table class="table table-condensed">
	<% flash.each do |type, content| %>
    <% if content.respond_to?('each') 
        content.each do |item| %>
            <%= render 'layouts/alert', 
                type: type,
                content: item %>
        <% end %>
    <% else %>
        <%= render 'layouts/alert', 
                type: type,
                content: content %>
    <% end %>

<% end %>
  <thead>
		<tr>
			<th style="text-align:center"> Profissão</th>
			<th style="text-align:center"> Editar </th>
			<th style="text-align:center"> Excluir </th>
		</tr>
	</thead>
  	<% if @professions.empty? %>
		<tr>
			<td colspan="3">
				<br>
				<font color="red" style="bold">Nenhum Profissão cadastrada.</font>
			</td>
		</tr>
	<% else %>
	    <% @professions.each do |profession| %>
	      <tr>
	        <td><%= profession.profissao %></td>
	        <td align="center"><%= link_to ' ', edit_profession_path(profession), 
	        	class: 'glyphicon glyphicon-pencil' %></td>
	        <td align="center"><%= link_to profession_path(profession), 
				method: :delete,
				data: { confirm: 'Tem certeza?' } do %>
				<span class="glyphicon glyphicon-trash"></span>
			<% end %></td>
	      </tr>
	    <% end %>
   <% end %>
</table>

app/views/professions/new.html.erb
<table class="table">
	<tr>
		<td>
			<%= image_tag("LogoGSAdvogados.png") %>
		</td>
	</tr>
	<tr>
		<td style="text-align:left">
			<h3>Nova Profissão</h3>
		</td>
	</tr>
</table>
<div class="navbar navbar-fixed-bottom container">
	<button id="saveButton" class="btn btn-primary glyphicon glyphicon-floppy-disk"> Salvar</button>
	<%= link_to ' Lista de Procurações', procurements_path, class: 'btn btn-default glyphicon glyphicon-list-alt' %>
	<%= link_to ' Voltar', professions_path, class: 'btn btn-default glyphicon glyphicon-arrow-left' %>
</div>
<%= render 'form' %>

app/views/professions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profissao:</strong>
  <%= @profession.profissao %>
</p>

<%= link_to 'Edit', edit_profession_path(@profession) %> |
<%= link_to 'Back', professions_path %>